apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ .Release.Namespace }}
data:
  DB_NAME: {{ .Values.backend.database.name | quote }}
  DB_PORT: {{ .Values.backend.database.port | quote }}
  DB_HOST: {{ .Values.backend.database.host | quote }}



