apiVersion: v1
kind: Secret
metadata:
  name: postgres
type: Opaque
data:
  POSTGRES_USER: cGF0cm9uZXNfMXBhcmNpYWw=   # base64 de "patrones_1parcial"
  POSTGRES_PASSWORD: cGFyY2lhbDE=           # base64 de "parcial1"
