apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 80          # Puerto que expondrá el Service
      targetPort: 8080  # Puerto del contenedor del backend
      protocol: TCP
