apiVersion: v2
name: pedido-app
description: Chart para desplegar la app de pedidos (frontend + backend)
type: application
version: 0.3.3
appVersion: "2.0.0"



dependencies:
  - name: postgresql
    version: 15.5.22
    repository: https://charts.bitnami.com/bitnami
