replicaCount: 3

image:
  backend:
    tag: "prod"
  frontend:
    tag: "prod"

ingress:
  host: pedido.com

resources:
  backend:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
  frontend:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "100m"
      memory: "128Mi"

backend:
  database:
    name: patrones
    port: 5432
    host: pedido-app-prod-postgresql

