replicaCount: 3
image:
  backend:
    repository: dani008/fastapi-backend
    tag: "1.0.0"
  frontend:
    repository: dani008/frontend
    tag: "1.0.1"


ingress:
  host: pedido.com

resources:
  backend:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
  frontend:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "100m"
      memory: "128Mi"

backend:
  database:
    name: patrones
    port: 5432
    host: pedido-app-prod-postgresql

