apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pedido-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Tw3kda/PARCIAL_CHARTS_PATRONES-AVANZADOS.git   # cambia con tu repo real
    targetRevision: HEAD
    path: pedido-app
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: pedido-dev
  syncPolicy:
    automated:             # ArgoCD sincroniza automáticamente
      prune: true          # elimina recursos obsoletos
      selfHeal: true       # corrige drift
    syncOptions:
      - CreateNamespace=true
